"""
Evaluator Agent implementation.

The Evaluator analyzes the base model and generates evaluation criteria,
including Guideline.md and Evaluate.py for quality control.
"""

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from pathlib import Path

from piano.agents.base import BaseAgent, AgentContext, AgentRole, AgentMessage, MessageType
from piano.agents.prompts.evaluator import EVALUATOR_PROMPTS


@dataclass
class ModelAnalysis:
    """Analysis results from the Evaluator."""
    problem_type: str = ""
    geometry_description: str = ""
    critical_features: List[str] = field(default_factory=list)
    mesh_quality_bounds: Dict[str, float] = field(default_factory=dict)
    material_ranges: Dict[str, Dict[str, float]] = field(default_factory=dict)
    allowable_modifications: Dict[str, Any] = field(default_factory=dict)
    success_thresholds: Dict[str, float] = field(default_factory=dict)
    raw_analysis: str = ""


@dataclass
class EvaluationCriteria:
    """Evaluation criteria generated by the Evaluator."""
    guidelines_md: str = ""
    evaluate_py: str = ""
    analysis: Optional[ModelAnalysis] = None


class EvaluatorAgent(BaseAgent[EvaluationCriteria]):
    """
    Evaluator Agent that analyzes base models and generates evaluation criteria.

    Responsibilities:
    1. Analyze the base .inp model structure
    2. Generate Guideline.md with quality constraints
    3. Generate Evaluate.py scoring script
    4. Review evaluation results
    """

    def __init__(
        self,
        model: str = "claude-3-opus-20240229",
        temperature: float = 0.2,
        **kwargs,
    ):
        super().__init__(
            role=AgentRole.EVALUATOR,
            model=model,
            temperature=temperature,
            **kwargs,
        )

    def get_system_prompt(self) -> str:
        return EVALUATOR_PROMPTS["system"]

    def build_user_prompt(self, context: AgentContext, **kwargs) -> str:
        task = kwargs.get("task", "analyze_model")

        if task == "analyze_model":
            return self._build_analyze_prompt(context, kwargs)
        elif task == "generate_guidelines":
            return self._build_guidelines_prompt(context, kwargs)
        elif task == "generate_evaluate_script":
            return self._build_evaluate_script_prompt(context, kwargs)
        elif task == "review_evaluation":
            return self._build_review_prompt(context, kwargs)
        else:
            raise ValueError(f"Unknown task: {task}")

    def _build_analyze_prompt(self, context: AgentContext, kwargs: Dict) -> str:
        model_info = context.model_info

        # Extract statistics from model info
        num_nodes = model_info.get("num_nodes", 0)
        num_elements = model_info.get("num_elements", 0)
        x_bounds = model_info.get("x_bounds", (0, 0))
        y_bounds = model_info.get("y_bounds", (0, 0))
        element_type = model_info.get("element_type", "unknown")
        materials = model_info.get("materials", {})
        bcs = model_info.get("boundary_conditions", {})

        # Format materials info
        materials_info = ""
        for name, props in materials.items():
            materials_info += f"- {name}: {props}\n"
        if not materials_info:
            materials_info = "No materials defined"

        # Format BC info
        bc_info = ""
        for name, bc_data in bcs.items():
            bc_info += f"- {name}: {bc_data}\n"
        if not bc_info:
            bc_info = "No boundary conditions defined"

        return EVALUATOR_PROMPTS["analyze_model"].format(
            model_info=str(model_info),
            num_nodes=num_nodes,
            num_elements=num_elements,
            x_min=x_bounds[0],
            x_max=x_bounds[1],
            y_min=y_bounds[0],
            y_max=y_bounds[1],
            element_type=element_type,
            materials_info=materials_info,
            bc_info=bc_info,
        )

    def _build_guidelines_prompt(self, context: AgentContext, kwargs: Dict) -> str:
        analysis = kwargs.get("analysis", "")
        return EVALUATOR_PROMPTS["generate_guidelines"].format(analysis=analysis)

    def _build_evaluate_script_prompt(self, context: AgentContext, kwargs: Dict) -> str:
        guidelines = kwargs.get("guidelines", "")
        return EVALUATOR_PROMPTS["generate_evaluate_script"].format(guidelines=guidelines)

    def _build_review_prompt(self, context: AgentContext, kwargs: Dict) -> str:
        return EVALUATOR_PROMPTS["review_evaluation"].format(
            solution_id=kwargs.get("solution_id", ""),
            evaluation_results=kwargs.get("evaluation_results", ""),
            metrics=kwargs.get("metrics", ""),
        )

    def parse_response(self, response: str) -> EvaluationCriteria:
        """Parse the LLM response into EvaluationCriteria."""
        criteria = EvaluationCriteria()

        # Check if this is a guidelines response
        if "# Guideline" in response or "## Mesh Quality" in response:
            criteria.guidelines_md = response

        # Check if this is an evaluate script response
        if "def evaluate_solution" in response:
            # Extract Python code block
            code_match = re.search(r'```python\s*(.*?)\s*```', response, re.DOTALL)
            if code_match:
                criteria.evaluate_py = code_match.group(1)
            else:
                # Try to extract code without markdown
                criteria.evaluate_py = response

        # Check if this is an analysis response
        if "Model Classification" in response or "Problem type" in response:
            criteria.analysis = self._parse_analysis(response)

        return criteria

    def _parse_analysis(self, response: str) -> ModelAnalysis:
        """Parse model analysis from response."""
        analysis = ModelAnalysis(raw_analysis=response)

        # Extract problem type
        type_match = re.search(
            r'(?:Problem type|Type):\s*([^\n]+)',
            response, re.IGNORECASE
        )
        if type_match:
            analysis.problem_type = type_match.group(1).strip()

        # Extract mesh quality bounds
        jacobian_match = re.search(
            r'(?:Minimum Jacobian|Jacobian)[:\s]+([0-9.]+)',
            response, re.IGNORECASE
        )
        if jacobian_match:
            analysis.mesh_quality_bounds["min_jacobian"] = float(jacobian_match.group(1))

        aspect_match = re.search(
            r'(?:Maximum aspect ratio|Aspect ratio)[:\s]+([0-9.]+)',
            response, re.IGNORECASE
        )
        if aspect_match:
            analysis.mesh_quality_bounds["max_aspect_ratio"] = float(aspect_match.group(1))

        # Extract delta_R range
        delta_r_match = re.search(
            r'delta_R[:\s]+\[([0-9.-]+),\s*([0-9.]+)\]',
            response, re.IGNORECASE
        )
        if delta_r_match:
            analysis.allowable_modifications["delta_R_min"] = float(delta_r_match.group(1))
            analysis.allowable_modifications["delta_R_max"] = float(delta_r_match.group(2))

        return analysis

    async def analyze_model(self, context: AgentContext) -> ModelAnalysis:
        """Analyze a model and return the analysis."""
        criteria = await self.execute(context, task="analyze_model")
        return criteria.analysis or ModelAnalysis()

    async def generate_guidelines(
        self,
        context: AgentContext,
        analysis: str,
    ) -> str:
        """Generate Guideline.md based on analysis."""
        criteria = await self.execute(context, task="generate_guidelines", analysis=analysis)
        return criteria.guidelines_md

    async def generate_evaluate_script(
        self,
        context: AgentContext,
        guidelines: str,
    ) -> str:
        """Generate Evaluate.py based on guidelines."""
        criteria = await self.execute(
            context,
            task="generate_evaluate_script",
            guidelines=guidelines
        )
        return criteria.evaluate_py

    async def full_evaluation_setup(
        self,
        context: AgentContext,
        output_dir: str,
    ) -> EvaluationCriteria:
        """
        Perform full evaluation setup: analyze, generate guidelines, generate script.

        Args:
            context: Agent context with model info
            output_dir: Directory to write output files

        Returns:
            EvaluationCriteria with all generated content
        """
        # Step 1: Analyze model
        analysis = await self.analyze_model(context)

        # Step 2: Generate guidelines
        guidelines = await self.generate_guidelines(
            context,
            analysis=analysis.raw_analysis
        )

        # Step 3: Generate evaluation script
        evaluate_script = await self.generate_evaluate_script(
            context,
            guidelines=guidelines
        )

        # Write outputs
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        guidelines_path = output_path / "Guideline.md"
        guidelines_path.write_text(guidelines, encoding="utf-8")

        evaluate_path = output_path / "Evaluate.py"
        evaluate_path.write_text(evaluate_script, encoding="utf-8")

        return EvaluationCriteria(
            guidelines_md=guidelines,
            evaluate_py=evaluate_script,
            analysis=analysis,
        )

    def create_model_info(self, manager) -> Dict[str, Any]:
        """
        Create model info dict from a MeshManager instance.

        Args:
            manager: MeshManager instance (e.g., MFEMManager)

        Returns:
            Dict with model information for context
        """
        model_info = {
            "num_nodes": 0,
            "num_elements": 0,
            "x_bounds": (0.0, 0.0),
            "y_bounds": (0.0, 0.0),
            "element_type": "unknown",
            "materials": {},
            "boundary_conditions": {},
        }

        if manager.nodes is not None:
            coords = manager.nodes.data
            model_info["num_nodes"] = len(coords)
            if len(coords) > 0:
                model_info["x_bounds"] = (float(coords[:, 0].min()), float(coords[:, 0].max()))
                model_info["y_bounds"] = (float(coords[:, 1].min()), float(coords[:, 1].max()))

        if manager.elements is not None:
            model_info["num_elements"] = len(manager.elements.ids)
            model_info["element_type"] = manager.elements.element_type

        for name, material in manager.materials.items():
            model_info["materials"][name] = material.data

        for name, bc in manager.boundary_conditions.items():
            model_info["boundary_conditions"][name] = bc.data

        return model_info
